spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: "classpath:/config"
logging:
  level:
    org.springframework.web: TRACE
server:
  port: 8071




